#ifndef __SYSCALLID_H__
#define __SYSCALLID_H__


enum {CHECK_KEY, GET_KEY, BACK_SPACE, PRINT_CHAR, UPDATE_CURSOR, PRINT_TO_TERMINAL,
	  UPDATE_TIME, GET_TIME,
	  FORK, FORK_T, GET_PID, EXIT_PROC, PROC_SLEEP,
	  SEM};

#endif
